### ISSUE TITLE
TODO: Add youtube link.

### ISSUE THREAD

**Issue by SylvainCorlay** [jupytercon/jupytercon.github.io#41]

**Comment by martinRenou** [comment]
What is the YouTube link? Is there a JupyterCon channel?

**Comment by SylvainCorlay** [comment]
Maybe not yet

**Comment by maartenbreddels** [comment]
So we only need to add the youtube link now, when we have it.

**Comment by marimeireles** [comment]
Is the youtube link supposed to be on top of that berlin shutterstock video?

**Comment by martinRenou** [comment]
In the menu, next to the Twitter link
